# Generated by Django 4.0.3 on 2022-05-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_userplant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='season',
            field=models.CharField(choices=[('W', 'Winter'), ('SP', 'Spring'), ('SU', 'Summer'), ('A', 'Autumn'), ('unknown', 'Unknown')], default='SU', max_length=50, verbose_name='Planting Season'),
        ),
    ]
