# Generated by Django 4.0.3 on 2022-05-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_info_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='season',
            field=models.CharField(choices=[(None, '(Unknown)'), ('W', 'Winter'), ('SP', 'Spring'), ('SU', 'Summer'), ('AU', 'Autumn')], default='SU', max_length=3, verbose_name='Planting Season'),
        ),
    ]
