# Generated by Django 4.0.3 on 2022-05-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_info_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edible',
            name='are_flowers_edible',
            field=models.CharField(choices=[(None, '(Unknown)'), ('Y', 'Yes'), ('N', 'No'), ('NA', 'Not Applicable'), ('P', 'Partially Edible'), ('RP', 'Requires Preperation'), ('PRP', 'Partially Edible But Requires Preperation')], default='(Unknown)', max_length=3),
        ),
        migrations.AlterField(
            model_name='edible',
            name='are_leaves_edible',
            field=models.CharField(choices=[(None, '(Unknown)'), ('Y', 'Yes'), ('N', 'No'), ('NA', 'Not Applicable'), ('P', 'Partially Edible'), ('RP', 'Requires Preperation'), ('PRP', 'Partially Edible But Requires Preperation')], default='(Unknown)', max_length=3),
        ),
        migrations.AlterField(
            model_name='edible',
            name='are_roots_edible',
            field=models.CharField(choices=[(None, '(Unknown)'), ('Y', 'Yes'), ('N', 'No'), ('NA', 'Not Applicable'), ('P', 'Partially Edible'), ('RP', 'Requires Preperation'), ('PRP', 'Partially Edible But Requires Preperation')], default='(Unknown)', max_length=3),
        ),
        migrations.AlterField(
            model_name='edible',
            name='are_seeds_edible',
            field=models.CharField(choices=[(None, '(Unknown)'), ('Y', 'Yes'), ('N', 'No'), ('NA', 'Not Applicable'), ('P', 'Partially Edible'), ('RP', 'Requires Preperation'), ('PRP', 'Partially Edible But Requires Preperation')], default='(Unknown)', max_length=3),
        ),
        migrations.AlterField(
            model_name='edible',
            name='is_fruit_edible',
            field=models.CharField(choices=[(None, '(Unknown)'), ('Y', 'Yes'), ('N', 'No'), ('NA', 'Not Applicable'), ('P', 'Partially Edible'), ('RP', 'Requires Preperation'), ('PRP', 'Partially Edible But Requires Preperation')], default='(Unknown)', max_length=3),
        ),
    ]
